# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c069f3e8cda87c68cedee554b1098612b7cd573716c1e75496a7d0eb418f1fca5ece5c51e8a0245d409d02608cae4456df63dc8dcd7fa2a31f1c6cdad6be34

test:
  secret_key_base: 8ba231208d7a834cbf6cbef07fbe9acf9f6fb4936752882e91fdee0d99fa9dd9e065e469c0145ded6bf86dbce34bd422e4461f27f3c5dea5ef1fe355d42808ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
